language: node_js
node_js:
  - "12"
cache:
  directories:
    - node_modules
    - news-bot/node_modules
install:
    - npm install -g serverless
    - travis_retry npm install
    - cd news-bot
    - npm install --save node-fetch
    - travis_retry npm install
    - cd -
script:
    - cd news-bot
    - serverless deploy
    - cd -
